/* Produce an integrated package and a BW2-only runtime from the accepted snapshot. */
const fs=require('fs'),path=require('path'),crypto=require('crypto'),acorn=require('acorn'),postcss=require('postcss');
const root=__dirname,input=path.join(root,'HUD黑白2版-第一版'),out=path.join(root,'黑白2双版本-v0.4.2');fs.mkdirSync(out,{recursive:true});
const payload=JSON.parse(fs.readFileSync(path.join(input,'宝可梦HUD-黑白2版.json'),'utf8'));const full=payload.content;let code=full;const report={ui:'0.4.2',retainsRequiredNativeBusiness:true,removedFunctions:[],removedVariables:[],removedSvgKeys:[],cssRemovedDeclarations:0};
function parse(){return acorn.parse(code,{ecmaVersion:'latest'});}
function walk(n,visit,parent){if(!n||!n.type)return;visit(n,parent);for(const v of Object.values(n))if(Array.isArray(v))v.forEach(x=>walk(x,visit,n));else if(v&&v.type)walk(v,visit,n);}
function edits(list){list.sort((a,b)=>b.start-a.start);let last=Infinity;for(const edit of list){if(edit.end>last)throw Error('Overlapping edits');code=code.slice(0,edit.start)+(edit.text||'')+code.slice(edit.end);last=edit.start;}}
function replaceFunction(name,text){let node;walk(parse(),n=>{if(n.type==='FunctionDeclaration'&&n.id.name===name)node=n;});if(!node)throw Error('Missing '+name);edits([{start:node.start,end:node.end,text}]);}
function exact(oldText,newText){if(code.split(oldText).length!==2)throw Error('Missing/ambiguous standalone hook: '+oldText.slice(0,60));code=code.replace(oldText,newText);}
// An independent runtime cannot load an older downloaded full core from a slot.
const bootstrap=code.indexOf('\nvar PK_BOOT_DELEGATED=null;');if(bootstrap<0)throw Error('Missing bootstrap');code=code.slice(0,bootstrap)+"\nrunPkmHud({coreReady:function(){},ready:function(){},reportError:function(){}});\n})();\n";
// Remove the embedded compatibility copy; executable UI remains exactly once.
let packageStatement;walk(parse(),(n,parent)=>{if(n.type==='VariableDeclarator'&&n.id.name==='PK_BEAUTY_PACKAGE')packageStatement=parent;});if(!packageStatement)throw Error('Missing compatibility package');edits([{start:packageStatement.start,end:packageStatement.end}]);
const updateStartMarker=code.indexOf('/*KOJI_UPDATE_RUNTIME_BEGIN*/'),updateEndMarker=code.indexOf('/*KOJI_UPDATE_RUNTIME_END*/');if(updateStartMarker<0||updateEndMarker<0)throw Error('Missing shared update runtime');code=code.slice(0,updateStartMarker)+code.slice(updateEndMarker+'/*KOJI_UPDATE_RUNTIME_END*/'.length);
replaceFunction('bw2AdaptCore','');
exact('try{pkReadUpdateCache();}catch(e){}','');exact('  try{pkAutoCheckUpdate();}catch(e){}','');
exact('pkBeautyBindUpdateUI(app);','');
code=code.replace(/\bapplyFabUpdateBadge\(\);/g,'');
// Remove settings update section and unused theme computation (fixed BW2 palette).
let settings;walk(parse(),n=>{if(n.type==='FunctionDeclaration'&&n.id.name==='settingsHTML')settings=n;});let settingsText=code.slice(settings.start,settings.end);const updateStart=settingsText.indexOf('<div class="set-title">黑白2版与原版核心更新</div>'),updateEnd=settingsText.indexOf('<div class="set-title">开发者选项</div>',updateStart);if(updateStart<0||updateEnd<0)throw Error('Missing update settings');settingsText=settingsText.slice(0,updateStart)+'<div class="set-title">版本</div><div class="dim">黑白2独立版 v0.4.2 · 通过重新导入交付文件更新</div>'+settingsText.slice(updateEnd);settingsText=settingsText.replace(/  var themeHue=.*\n/,'').replace(/  var presetBtns=.*\n/,'');replaceFunction('settingsHTML',settingsText);
const themeStart=code.indexOf("var th=pageOverlay.querySelector('#pk-theme-hue');"),themeEnd=code.indexOf("var fio=pageOverlay.querySelector('[data-fab-img-open]');",themeStart);if(themeStart<0||themeEnd<0)throw Error('Missing fixed-theme hooks');code=code.slice(0,themeStart)+code.slice(themeEnd);code=code.replace(/\bpkThemeApplyScheme\(\);/g,'');
// Retain only the detail data fragments used by our renderer, not the old modal.
replaceFunction('bw2LegacyDetailHTML',`function bw2DetailFieldsHTML(c){
 var ball=c.ball?'<span class="item-icon placeholder item-wiki" data-item="'+esc(c.ball)+'" data-item-en="'+esc(c.ballEn||'')+'" data-cls="ball-icon dt-ball">?</span>':'';
 var rows='<div class="row"><span class="k">HP</span><span class="v">'+c.hpCur+'/'+c.hpMax+'</span></div>'+(c.status?'<div class="row"><span class="k">异常状态</span><span class="v">'+statusTag(c.status)+'</span></div>':'')+(c.hatch?'<div class="row"><span class="k">孵化剩余</span><span class="v">'+esc(c.hatch)+'</span></div>':'')+(c.partner?'<div class="row"><span class="k">搭档倾向</span><span class="v">'+esc(c.partner)+'</span></div>':'');
 return '<div class="modal-body"><div class="dt-top">'+ball+'</div><div class="dt-sprite">'+pkImgHTML(c.species,c.icon,c.shiny,'dt-big')+'</div>'+moveGridHTML(c.skills)+'<div class="row">'+(c.ability?'<span class="abi-link" data-ability="'+esc(c.ability)+'">'+esc(c.ability)+'</span>':'')+'</div><div class="row">'+(c.nature?'<span class="abi-link" data-nature="'+esc(c.nature)+'">'+esc(c.nature)+'</span>':'')+'</div>'+rows+'</div>';
}`);exact('holder.innerHTML=bw2LegacyDetailHTML(c);','holder.innerHTML=bw2DetailFieldsHTML(c);');exact('holder.innerHTML=bw2LegacyDetailHTML(card);','holder.innerHTML=bw2DetailFieldsHTML(card);');
// Remove update-only event bindings; no hidden installer handlers remain.
let removals=[];const updateVars=new Set(['pku','pkd','psc','pkr','pdu','pkc','pkc2']);walk(parse(),(n,parent)=>{if(n.type==='VariableDeclaration'&&n.declarations.every(d=>d.id.type==='Identifier'&&updateVars.has(d.id.name)))removals.push({start:n.start,end:n.end});if(n.type==='IfStatement'&&n.test.type==='Identifier'&&updateVars.has(n.test.name))removals.push({start:n.start,end:n.end});});edits(removals);
const commandKeys=new Set(['training','dodge','initiative','guard','revive','mega','clash']);let commandObject;walk(parse(),n=>{if(n.type==='VariableDeclarator'&&n.id.name==='BW2_COMMAND_ICONS')commandObject=n.init;});if(!commandObject)throw Error('Missing command images');report.removedCommandIconKeys=[];edits([{start:commandObject.start,end:commandObject.end,text:'{'+commandObject.properties.filter(p=>{const key=p.key.name||p.key.value;if(!commandKeys.has(key))report.removedCommandIconKeys.push(key);return commandKeys.has(key);}).map(p=>code.slice(p.start,p.end)).join(',')+'}'}]);
// One shared menu SVG catalogue: command PNGs use none of the old command SVGs.
const keepIcons=new Set(['settings','badge','pokedex','breeding','bag','box','map','typechart']);let iconObject;walk(parse(),n=>{if(n.type==='FunctionDeclaration'&&n.id.name==='swshIcon')walk(n.body,x=>{if(x.type==='VariableDeclarator'&&x.id.name==='art')iconObject=x.init;});});if(!iconObject)throw Error('Missing icon catalogue');const iconProperties=iconObject.properties.filter(p=>{const key=p.key.name||p.key.value;if(!keepIcons.has(key))report.removedSvgKeys.push(key);return keepIcons.has(key);});edits([{start:iconObject.start,end:iconObject.end,text:'{'+iconProperties.map(p=>code.slice(p.start,p.end)).join(',')+'}'}]);
// Conservative function reachability, including callbacks named in HTML strings.
// False positives retain code; dynamic function names in string literals are roots.
const ast=parse();let run,outer;walk(ast,(n,p)=>{if(n.type==='FunctionDeclaration'&&n.id.name==='runPkmHud'){run=n;outer=p;}});const candidates=[...outer.body.filter(n=>n.type==='FunctionDeclaration'),...run.body.body.filter(n=>n.type==='FunctionDeclaration')],candidateSet=new Set(candidates),names=new Set(candidates.map(n=>n.id.name));
function refs(node,skip){const result=new Set();function visit(n,p,key){if(!n||!n.type||skip&&candidateSet.has(n))return;if(n.type==='Identifier'){const nonref=p&&((p.type==='MemberExpression'&&p.property===n&&!p.computed)||(p.type==='Property'&&p.key===n&&!p.computed&&!p.shorthand)||(p.type==='VariableDeclarator'&&p.id===n)||(p.type==='FunctionDeclaration'&&p.id===n));if(!nonref&&names.has(n.name))result.add(n.name);}if(n.type==='Literal'&&typeof n.value==='string'){for(const word of n.value.match(/[A-Za-z_$][\w$]*/g)||[])if(names.has(word))result.add(word);}for(const [k,v]of Object.entries(n))if(Array.isArray(v))v.forEach(x=>visit(x,n,k));else if(v&&v.type)visit(v,n,k);}visit(node);return result;}
const live=refs(ast,true),byName=new Map(candidates.map(n=>[n.id.name,n]));const queue=[...live];while(queue.length){const fn=byName.get(queue.pop());if(!fn)continue;const fnRefs=new Set();for(const stmt of fn.body.body)for(const r of refs(stmt,true))fnRefs.add(r);for(const ref of fnRefs)if(!live.has(ref)){live.add(ref);queue.push(ref);}}
removals=candidates.filter(n=>!live.has(n.id.name)).map(n=>{report.removedFunctions.push(n.id.name);return {start:n.start,end:n.end};});edits(removals);
// Drop unused, side-effect-free catalogue/config declarations in runtime scopes.
function pure(n){if(!n)return true;if(n.type==='Literal')return true;if(n.type==='ArrayExpression')return n.elements.every(pure);if(n.type==='ObjectExpression')return n.properties.every(p=>p.type==='Property'&&!p.computed&&pure(p.value));if(n.type==='UnaryExpression')return pure(n.argument);return false;}
for(let pass=0;pass<4;pass++){
 const tree=parse(),uses=new Map();walk(tree,(n,p)=>{if(n.type==='Identifier'&&!(p&&(p.type==='VariableDeclarator'&&p.id===n||p.type==='FunctionDeclaration'&&p.id===n||p.type==='MemberExpression'&&p.property===n&&!p.computed||p.type==='Property'&&p.key===n&&!p.computed&&!p.shorthand)))uses.set(n.name,(uses.get(n.name)||0)+1);});let currentRun,currentOuter;walk(tree,(n,p)=>{if(n.type==='FunctionDeclaration'&&n.id.name==='runPkmHud'){currentRun=n;currentOuter=p;}});removals=[];for(const n of [...currentOuter.body,...currentRun.body.body])if(n.type==='VariableDeclaration'){const keep=n.declarations.filter(d=>{const unused=d.id.type==='Identifier'&&!uses.has(d.id.name)&&pure(d.init);if(unused)report.removedVariables.push(d.id.name);return !unused;});if(keep.length!==n.declarations.length)removals.push({start:n.start,end:n.end,text:keep.length?n.kind+' '+keep.map(d=>code.slice(d.start,d.end)).join(',')+';':''});}if(!removals.length)break;edits(removals);
}
// Collapse CSS into a single stylesheet. Only unconditional exact-selector overrides
// are deduplicated; conditions and !important precedence remain intact.
let cssVar,cssAdds=[];walk(parse(),n=>{if(n.type==='VariableDeclarator'&&n.id.name==='css'&&n.init.type==='Literal'&&typeof n.init.value==='string'&&n.init.value.includes('#pkm-hud-win'))cssVar=n;if(n.type==='ExpressionStatement'&&n.expression.type==='AssignmentExpression'&&n.expression.left.name==='css'&&n.expression.operator==='+=')cssAdds.push(n);});if(!cssVar)throw Error('Missing CSS');let css=Function('return '+code.slice(cssVar.init.start,cssVar.init.end))();for(const n of cssAdds){if(n.expression.right.type!=='Literal')throw Error('Dynamic CSS must be retained explicitly');css+=n.expression.right.value;}const knownTokens=new Set();walk(parse(),n=>{if(n.start===cssVar.init.start&&n.end===cssVar.init.end||cssAdds.some(stmt=>n.start===stmt.expression.right.start&&n.end===stmt.expression.right.end))return;if(n.type==='Literal'&&typeof n.value==='string')for(const token of n.value.match(/[A-Za-z_][\w-]*/g)||[])knownTokens.add(token);});report.removedCssSelectors=[];const sheet=postcss.parse(css),latest=new Map();sheet.walkRules(rule=>{const unused=rule.selector.split(',').every(branch=>{const match=branch.trim().match(/^[.#]([A-Za-z_][\w-]*)/);return match&&!knownTokens.has(match[1])&&![...knownTokens].some(token=>token.endsWith('-')&&match[1].startsWith(token));});if(unused){report.removedCssSelectors.push(rule.selector);rule.remove();}});sheet.walkRules(rule=>{if(rule.parent!==sheet)return;rule.walkDecls(d=>{const key=rule.selector+'\0'+d.prop,previous=latest.get(key);if(previous&&(!previous.important||d.important)){previous.remove();report.cssRemovedDeclarations++;}latest.set(key,d);});});sheet.walkComments(n=>n.remove());sheet.walkRules(r=>{if(!r.nodes.length)r.remove();});css=sheet.toString();edits([{start:cssVar.init.start,end:cssVar.init.end,text:JSON.stringify(css)},...cssAdds.map(n=>({start:n.start,end:n.end}))]);
// Preserve user preference/asset stores; a distinct runtime name is only metadata.
const nativeCore=full.match(/var PK_VER='([^']+)'/)[1];
exact("var PK_VER='"+nativeCore+"';","var PK_VER='"+nativeCore+"';\nvar PK_BEAUTY_VER='0.4.2';\nvar BW2_STANDALONE=true;");
report.removedVariables=report.removedVariables.filter(function(name){return name!=='PK_BEAUTY_VER';});new Function(code);acorn.parse(code,{ecmaVersion:'latest'});
const forbidden=['PK_BEAUTY_PACKAGE','pkBeautyBuildRemote','bw2LegacyDetailHTML','PK_BOOT_DELEGATED','function pkDoUpdate','function pkCheckUpdate','data-pk-check-update'];for(const token of forbidden)if(code.includes(token)){console.log(code.slice(code.indexOf(token)-100,code.indexOf(token)+150));throw Error('Unexpected standalone dependency: '+token);}
function writeVersion(folder,name,content,id){const d=path.join(out,folder);fs.mkdirSync(d,{recursive:true});const p={...payload,id,name,content,info:folder==='独立版'?'黑白2 UI v0.4.2 独立运行版：提取必要原版业务与当前展示资源，不包含兼容更新包；通过重新导入更新。':'黑白2 UI v0.4.2 完整适配版，包含原版核心与兼容更新机制。'};fs.writeFileSync(path.join(d,'宝可梦HUD-'+folder+'.json'),JSON.stringify(p,null,2));fs.writeFileSync(path.join(d,'宝可梦HUD-'+folder+'.js'),content);return {jsBytes:Buffer.byteLength(content),jsonBytes:fs.statSync(path.join(d,'宝可梦HUD-'+folder+'.json')).size,sha256:crypto.createHash('sha256').update(content).digest('hex')};}
report.full=writeVersion('完整版','宝可梦HUD 黑白2完整版 v0.4.2',full,payload.id);const independentId=crypto.createHash('sha256').update(payload.id+':standalone').digest('hex').slice(0,32).replace(/(.{8})(.{4})(.{4})(.{4})(.{12})/,'$1-$2-$3-$4-$5');report.standalone=writeVersion('独立版','宝可梦HUD 黑白2独立版 v0.4.2',code,independentId);report.savedPercent=Number(((1-report.standalone.jsBytes/report.full.jsBytes)*100).toFixed(2));fs.writeFileSync(path.join(out,'构建与裁剪记录.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({out,full:report.full,standalone:report.standalone,savedPercent:report.savedPercent,removedFunctions:report.removedFunctions.length,removedVariables:report.removedVariables.length}));



