const fs=require('node:fs'),path=require('node:path');
const dir=path.join(__dirname,'HUD黑白2版-第一版');
const previewVersion=JSON.parse(fs.readFileSync(path.join(dir,'构建信息.json'),'utf8')).ui;
const team=[['君主蛇','serperior','草','',71,211,'胆小','茂盛','巨声:一般:特殊,能量球:草:特殊,龙之波动:龙:特殊,光合作用:草:变化'],['炎武王','emboar','火','格斗',72,260,'固执','猛火','火焰拳:火:物理,臂锤:格斗:物理,地震:地面:物理,守住:一般:变化'],['大剑鬼','samurott','水','',76,237,'认真','激流','冲浪:水:特殊,冰冻光束:冰:特殊,水流喷射:水:物理,守住:一般:变化'],['勇士雄鹰','braviary','一般','飞行',74,265,'爽朗','锐利目光','勇鸟猛攻:飞行:物理,蛮力:格斗:物理,羽栖:飞行:变化,守住:一般:变化'],['路卡利欧','lucario','格斗','钢',68,242,'固执','精神力','波导弹:格斗:特殊,神速:一般:物理,剑舞:一般:变化,守住:一般:变化'],['火神蛾','volcarona','虫','火',76,269,'胆小','火焰之躯','蝶舞:虫:变化,火焰放射:火:特殊,虫鸣:虫:特殊,守住:一般:变化']];
const sample={训练家:{名字:'伯劳',活力:3,活力上限:3,金钱:479810,徽章:'城都:飞翼徽章,昆虫徽章',身份:'训练家 / 千羽阁传人',声望:'3800 千羽流无言宗师',气场:'千羽：行动优先度提升，受到的伤害降低。',可命令等级:81},环境:{当前地点:'卡吉镇外围地下 · 水利枢纽7号深井B3层',日期:'第26天',时间:'晚上21:25'},队伍:{},附近宝可梦:{},背包:{伤药:{类型:'道具',数量:4}},盒子:{盒子1:{}},任务:{主线:'探索卡吉镇地下设施',支线:'寻找失踪的调查员'},世界事件:{附近遭遇:'前方传来野生宝可梦的声音',地区新闻:'城都地区气温略有回升',区域动态:'调查队正在巡查周边区域'}};
team.forEach((p,i)=>sample.队伍[String(i+1)]={名字:p[0],等级:p[4],HP:p[5]+'/'+p[5],性别:'♂',属性1:p[2],属性2:p[3],性格:p[6],特性:p[7],技能:p[8],经验:'3815/4161',亲密度:255,携带道具:i===0?'奇迹种子':'无',个体值:'HP:31/31,攻击:19/31,防御:28/31,特攻:30/31,特防:26/31,速度:31/31',图标:'https://play.pokemonshowdown.com/sprites/gen5/'+p[1]+'.png',精灵球:'精灵球'});
Object.assign(sample.队伍['1'],{图鉴编号:497,原训练家:'伯劳',训练家ID:'18098',相遇日期:'第18天',相遇地点:'卡吉镇',相遇等级:5,个性:'经常眺望远方。'});
[['咕咕','hoothoot','一般','飞行',4],['榛果球','pineco','虫','',3],['圆丝蛛','spinarak','虫','毒',2],['戴鲁比','houndour','恶','火',1]].forEach((p,i)=>sample.附近宝可梦[String(i+1)]={名字:p[0],属性1:p[2],属性2:p[3],数量:p[4],图标:'https://play.pokemonshowdown.com/sprites/gen5/'+p[1]+'.png'});
let code=fs.readFileSync(path.join(dir,'宝可梦HUD-黑白2版.js'),'utf8');
// The preview-only bridge exposes internal functions for automated checks.
code=code.replace('try{pkReadUpdateCache();}catch(e){}',"window.__BW2_TEST={identity:bw2DetailIdentity,refresh:pkRefreshData,render:render,build:pkBeautyBuildRemote,check:pkCheckUpdate,update:pkDoUpdate,detail:detailHTML,card:cardFromPkm,state:function(){return pkmHudClone(stat_data);},diagnostics:hudDiagSnapshot,dexRender:renderDexGrid};\ntry{pkReadUpdateCache();}catch(e){}");
const dataRev=code.match(/var PKM_DATA_REV='([^']+)'/)[1];
const dataFixture="localStorage.setItem('pk_gh_abil',"+JSON.stringify(JSON.stringify({rev:dataRev,data:[{name:'茂盛',en:'Overgrow',desc:'在危急时，草系技能的威力会提升。'}]}))+");localStorage.setItem('pk_gh_item',"+JSON.stringify(JSON.stringify({rev:dataRev,data:[{name:'奇迹种子',en:'Miracle Seed',desc:'携带后草属性招式的威力提升。'}]}))+");";
const fixture=`localStorage.setItem('pk_winmode','0');var previewState=${JSON.stringify(sample)};var previewWrites=0;var previewHandlers={};window.Mvu={getMvuData:()=>({stat_data:JSON.parse(JSON.stringify(previewState))}),replaceMvuData:(d)=>{previewState=d.stat_data;previewWrites++;return Promise.resolve();}};window.SillyTavern={getContext:()=>({chatId:'BW2_PREVIEW_ONLY',chat:[],characters:[],eventSource:{on:(n,f)=>{(previewHandlers[n]||(previewHandlers[n]=[])).push(f)},off:(n,f)=>{previewHandlers[n]=(previewHandlers[n]||[]).filter(x=>x!==f)}},eventTypes:{},setExtensionPrompt:()=>{}})};`;
const html='<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>黑白2 HUD 第一版预览</title><style>body{margin:0;background:#090f19;font-family:Arial,"Microsoft YaHei",sans-serif}.preview-note{color:#899daf;font-size:12px;max-width:640px;margin:20px auto 10px;padding:0 12px}.mes{max-width:640px;margin:0 auto 30px;padding:0 12px}.mes_text{margin:0}*{box-sizing:border-box}</style></head><body><p class="preview-note">黑白2 HUD v'+previewVersion+' · 示例数据预览；不连接你的聊天。可展开训练家、点击精灵查看统一详情、点击名称查看附加资料或进入菜单。</p><div class="mes" mesid="0" is_user="false"><div class="mes_text"></div></div><script>'+fixture.replaceAll('</script','<\\/script')+'</script><script>'+code.replaceAll('</script','<\\/script')+'</script></body></html>';
fs.writeFileSync(path.join(dir,'第一版预览.html'),html.replace('<script>','<script>'+dataFixture));
fs.writeFileSync(path.join(dir,'sample-state.json'),JSON.stringify(sample,null,2));
console.log('Preview written');

