const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('./browser-runtime.cjs');
(async()=>{const browser=await chromium.launch({headless:true,...require('./browser-runtime.cjs').launchOptions}),results=[];
try{for(const variant of ['完整版','独立版'])for(const mode of ['0','1'])for(const width of [950,360]){
 const page=await browser.newPage({viewport:{width,height:1300}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const html=fs.readFileSync(path.join(__dirname,'黑白2双版本-v0.4.2/'+variant+'/预览与测试.html'),'utf8').replace("localStorage.setItem('pk_winmode','0')",`localStorage.setItem('pk_winmode','${mode}')`).replace('var previewWrites=0;',"Object.assign(previewState.队伍['1'],{名字:'超级烈咬陆鲨X',是否Mega:true,携带道具:'烈咬陆鲨进化石X'});var previewWrites=0;");
 await page.route('**/*',async r=>{if(r.request().url().startsWith('http://firstpaint.test'))return r.fulfill({contentType:'text/html',body:html});if(r.request().resourceType()==='image'){await new Promise(resolve=>setTimeout(resolve,180));return r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"><circle cx="256" cy="256" r="256" fill="cyan"/></svg>'});}return r.fulfill({contentType:'application/json',body:'{"data":[]}'});});
 await page.goto('http://firstpaint.test');if(mode==='1')await page.locator('#pkm-hud-btn').click();await page.locator('.card-frame').first().waitFor();await page.waitForTimeout(300);
 const frames=await page.evaluate(async()=>{const frames=[];function snapshot(label){const d=document.querySelector('.bw2-detail'),r=d.querySelector('.bw2-summary-scene').getBoundingClientRect();frames.push({label,open:d.parentElement.classList.contains('open'),width:r.width,height:r.height,invalid:/NaN|Infinity/.test(d.getAttribute('style')),badgeWidth:d.querySelector('.bw2-state-badge img').getBoundingClientRect().width,geometry:Array.from(d.querySelectorAll('.bw2-scene-geometry,.bw2-upper-outline,.bw2-header-cap')).map(svg=>{const path=svg.querySelector('path'),rect=path.getBoundingClientRect();return {aspect:svg.getAttribute('preserveAspectRatio'),width:rect.width,left:rect.left};})});}document.querySelector('.card-frame').click();snapshot('synchronous');for(let i=0;i<3;i++){await new Promise(requestAnimationFrame);snapshot('frame'+i);}window.__BW2_TEST.render();snapshot('refresh');return frames;});
 await page.waitForTimeout(260);frames.push(await page.locator('.bw2-detail').evaluate(d=>({label:'images-loaded',open:d.parentElement.classList.contains('open'),width:d.querySelector('.bw2-summary-scene').getBoundingClientRect().width,height:d.querySelector('.bw2-summary-scene').getBoundingClientRect().height,invalid:/NaN|Infinity/.test(d.getAttribute('style')),badgeWidth:d.querySelector('.bw2-state-badge img').getBoundingClientRect().width,geometry:Array.from(d.querySelectorAll('.bw2-scene-geometry,.bw2-upper-outline,.bw2-header-cap')).map(svg=>{const path=svg.querySelector('path'),rect=path.getBoundingClientRect();return {aspect:svg.getAttribute('preserveAspectRatio'),width:rect.width,left:rect.left};})})));
 for(const f of frames){assert.ok(f.open&&!f.invalid&&f.width>250&&f.height>100,JSON.stringify({mode,width,f}));assert.ok(f.badgeWidth>5&&f.badgeWidth<40,JSON.stringify(f));assert.ok(Math.abs(f.width-frames[0].width)<1,JSON.stringify(frames));for(let i=0;i<f.geometry.length;i++){assert.equal(f.geometry[i].aspect,'none',JSON.stringify({mode,width,f}));assert.ok(Math.abs(f.geometry[i].width-frames[0].geometry[i].width)<1,JSON.stringify(frames));assert.ok(Math.abs(f.geometry[i].left-frames[0].geometry[i].left)<1,JSON.stringify(frames));}}assert.deepEqual(errors,[]);results.push({variant,mode,width,frames});await page.close();
}fs.writeFileSync(path.join(__dirname,'黑白2双版本-v0.4.2/详情首次绘制验证.json'),JSON.stringify({passed:true,results},null,2));console.log(JSON.stringify({passed:true,cases:results.length}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});


