const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const{chromium}=require('./browser-runtime.cjs');
const root=__dirname,out=path.join(root,'黑白2双版本-v0.4.8');
const palette={一般:'#A8A878',格斗:'#C03028',飞行:'#A890F0',毒:'#A040A0',地面:'#E0C068',岩石:'#B8A038',虫:'#A8B820',幽灵:'#705898',钢:'#B8B8D0',火:'#F08030',水:'#6890F0',草:'#78C850',电:'#F8D030',超能力:'#F85888',冰:'#98D8D8',龙:'#7038F8',恶:'#705848',妖精:'#EE99AC'};
(async()=>{const browser=await chromium.launch({headless:true,...require('./browser-runtime.cjs').launchOptions}),results=[];try{
for(const variant of ['完整版','独立版']){
 const page=await browser.newPage({viewport:{width:950,height:1300}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const html=fs.readFileSync(path.join(out,variant,'预览与测试.html'),'utf8');
 await page.route('**/*',r=>r.request().url().startsWith('http://palette.test')?r.fulfill({contentType:'text/html',body:html}):r.fulfill({contentType:r.request().resourceType()==='image'?'image/svg+xml':'application/json',body:r.request().resourceType()==='image'?'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><circle cx="50" cy="50" r="45" fill="cyan"/></svg>':'{"data":[]}'}));
 await page.goto('http://palette.test');await page.locator('.card-frame').first().click();await page.locator('.bw2-detail').waitFor();await page.waitForTimeout(100);await page.screenshot({path:path.join(out,variant,'属性配色预览.png')});
 const cases=await page.evaluate(async(palette)=>{const result=[],cell=document.querySelector('.bw2-detail .dt-move-cell');for(const [type,color]of Object.entries(palette)){cell.setAttribute('data-mvtype',type);await new Promise(requestAnimationFrame);const mark=cell.querySelector('.bw2-move-category'),frame=cell.querySelector('polygon'),chip=cell.querySelector('.type-chip,.move-type'),probe=document.createElement('span');probe.style.color=color;document.body.appendChild(probe);const expected=getComputedStyle(probe).color;probe.remove();result.push({type,expected,border:getComputedStyle(frame).stroke,icon:getComputedStyle(mark).color,chip:getComputedStyle(chip).backgroundColor});}cell.setAttribute('data-mvtype','unknown');await new Promise(requestAnimationFrame);result.push({type:'unknown',expected:'rgb(136, 136, 136)',border:getComputedStyle(cell.querySelector('polygon')).stroke,icon:getComputedStyle(cell.querySelector('.bw2-move-category')).color,chip:getComputedStyle(cell.querySelector('.type-chip,.move-type')).backgroundColor});return result;},palette);
 for(const c of cases){assert.equal(c.border,c.expected);assert.equal(c.icon,c.expected);assert.equal(c.chip,c.expected);}
 const cats=await page.evaluate(async()=>{const host=document.querySelector('.bw2-detail');['物理','特殊','变化'].forEach(cat=>{const cell=document.createElement('div');cell.className='move-cell';cell.dataset.mvtype='water';cell.dataset.mvcat=cat;cell.innerHTML='<span class="move-cat"><img class="move-cat-ic"></span>';host.appendChild(cell);});await new Promise(requestAnimationFrame);return Array.from(host.querySelectorAll('.bw2-colored-category')).map(svg=>({category:svg.getAttribute('aria-label'),color:getComputedStyle(svg).color,art:svg.innerHTML.length}));});assert.equal(cats.length,3);for(const c of cats){assert.equal(c.color,'rgb(104, 144, 240)');assert.ok(c.art>50);}assert.deepEqual(errors,[]);
 results.push({variant,cases,cats});await page.close();
}fs.writeFileSync(path.join(out,'招式属性配色验证.json'),JSON.stringify({passed:true,results},null,2));console.log(JSON.stringify({passed:true,variants:2,attributeCases:38,categoryCases:6}));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});


