const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const{chromium}=require('./browser-runtime.cjs');
const out=path.join(__dirname,'黑白2双版本-v0.3.10'),original=JSON.parse(fs.readFileSync(path.join(__dirname,'pkm-hud-upstream.json'),'utf8')).content;
(async()=>{const b=await chromium.launch({headless:true,...require('./browser-runtime.cjs').launchOptions});try{
 const p=await b.newPage({viewport:{width:950,height:1300}}),errors=[],calls={requests:0};p.on('pageerror',e=>errors.push(e.message));let remote=original,networkFail=false;
 const bridge="update:{check:pkCheckUpdate,auto:pkAutoCheckUpdate,install:pkDoUpdate,mode:function(mode){window.testUpdate={mode:mode,installed:[],written:[],copied:[]};pkInstallRecord=function(ver,content){testUpdate.installed.push({ver:ver,content:content});return new Promise(function(res,rej){setTimeout(function(){mode==='db-fail'?rej(new Error('mock db failure')):res(true);},50);});};pkUpdateScript=function(content){testUpdate.written.push(content);return mode==='write-fail'?Promise.resolve({ok:false}):Promise.resolve({ok:true});};diyCopyText=function(content,cb){testUpdate.copied.push(content);cb(true);};},snapshot:function(){return {prepared:pkBeautyPreparedContent,ver:pkBeautyPreparedVer,latest:pkLatestContent,log:document.getElementById('pk-update-msg').textContent};}},";
 const html=fs.readFileSync(path.join(out,'完整版/预览与测试.html'),'utf8').replace('window.__BW2_TEST={identity:','window.__BW2_TEST={'+bridge+'identity:');
 await p.route('**/*',async r=>{const u=r.request().url();if(u.startsWith('http://update.test'))return r.fulfill({contentType:'text/html',body:html});if(u.includes('/updates/bw2.json'))return r.fulfill({contentType:'application/json',body:JSON.stringify({schema:1,channel:'bw2',ui:'0.3.10',core:'3.3.1'})});if(u.includes('/pkm-hud/main/pkm-hud.js')){calls.requests++;await new Promise(res=>setTimeout(res,80));return networkFail?r.abort():r.fulfill({contentType:'text/javascript',body:remote});}return r.fulfill({contentType:r.request().resourceType()==='image'?'image/svg+xml':'application/json',body:r.request().resourceType()==='image'?'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"/>':'{"data":[]}'});});
 await p.goto('http://update.test');await p.locator('.bw2-console').waitFor();await p.waitForTimeout(200);await p.locator('.tab-btn[data-tab="4"]').click();await p.locator('[data-page="settings"]').click();await p.evaluate(()=>__BW2_TEST.update.mode('success'));
 assert.equal(await p.evaluate(()=>__BW2_TEST.update.install()),false);assert.equal(await p.evaluate(()=>testUpdate.installed.length),0);
 remote=original.replace("var PK_VER='3.3.1'","var PK_VER='3.3.2'");const before=calls.requests;const checks=await p.evaluate(()=>Promise.all([__BW2_TEST.update.check(),__BW2_TEST.update.check(),__BW2_TEST.update.auto()]));assert.deepEqual(checks,[true,true,true]);assert.equal(calls.requests-before,1);
 const ready=await p.evaluate(()=>__BW2_TEST.update.snapshot());assert.equal(ready.ver,'3.3.2');assert.equal(ready.latest,ready.prepared);assert.ok(ready.prepared.includes("var PK_BEAUTY_VER='0.3.10'"));assert.ok(ready.prepared.includes('brightness(0)!important'));new Function(ready.prepared);
 await p.locator('[data-pk-show-content]').click();await p.locator('[data-pk-copy-content]').click();assert.equal(await p.evaluate(()=>testUpdate.copied[0]),ready.prepared);await p.locator('.pkm-hud-overlay.open [data-close]').first().click();
 const installs=await p.evaluate(()=>Promise.all([__BW2_TEST.update.install(),__BW2_TEST.update.install()]));assert.deepEqual(installs,[true,false]);assert.equal(await p.evaluate(()=>testUpdate.installed.length),1);assert.equal(await p.evaluate(()=>testUpdate.written[0]),ready.prepared);
 await p.evaluate(()=>__BW2_TEST.update.mode('write-fail'));assert.equal(await p.evaluate(()=>__BW2_TEST.update.install()),true);assert.match((await p.evaluate(()=>__BW2_TEST.update.snapshot())).log,/本地更新/);
 await p.evaluate(()=>__BW2_TEST.update.mode('db-fail'));assert.equal(await p.evaluate(()=>__BW2_TEST.update.install()),false);assert.equal(await p.evaluate(()=>testUpdate.written.length),0);
 remote=fs.readFileSync(path.join(__dirname,'upstream-update-fixture.js'),'utf8');assert.ok(remote.includes("var PK_VER='3.3.19';"));
 assert.equal(await p.evaluate(()=>__BW2_TEST.update.check()),true);
 const actualReady=await p.evaluate(()=>__BW2_TEST.update.snapshot());assert.equal(actualReady.ver,'3.3.19');new Function(actualReady.prepared);
 const acorn=require('acorn');function nativeFunctions(source){const map={};function visit(n){if(!n||!n.type)return;if(n.type==='FunctionDeclaration')map[n.id.name]=source.slice(n.start,n.end);for(const v of Object.values(n))if(Array.isArray(v))v.forEach(visit);else if(v&&v.type)visit(v);}visit(acorn.parse(source,{ecmaVersion:'latest'}));return map;}
 const latestNative=nativeFunctions(remote),latestAdapted=nativeFunctions(actualReady.prepared);for(const name of ['cardHTML','teamHTML','storePkm','withdrawPkm','moveBoxPkm','equipPkm','hudAssertPokemonMutable','hudRecordAssetMutation','pkmHudPersistStatData','pkmHudAuthoritativeAssetMutation','resolvePkmImgs','resolveItemImgs'])assert.equal(latestAdapted[name],latestNative[name],name+' latest core preserved');
 await p.evaluate(()=>__BW2_TEST.update.mode('success'));assert.equal(await p.evaluate(()=>__BW2_TEST.update.install()),true);assert.equal(await p.evaluate(()=>testUpdate.written[0]),actualReady.prepared);
 fs.writeFileSync(path.join(out,'v3.3.19-合成验证.js'),actualReady.prepared);
 let latestHtml=html;const scriptStart=latestHtml.lastIndexOf('<script>'),scriptEnd=latestHtml.lastIndexOf('</script>');
 latestHtml=latestHtml.slice(0,scriptStart+8)+actualReady.prepared.replaceAll('</script','<\\/script')+latestHtml.slice(scriptEnd);
 const q=await b.newPage({viewport:{width:950,height:1300}}),latestErrors=[];q.on('pageerror',e=>latestErrors.push(e.message));
 await q.route('**/*',r=>r.request().url().startsWith('http://latest.test')?r.fulfill({contentType:'text/html',body:latestHtml}):r.fulfill({contentType:r.request().resourceType()==='image'?'image/svg+xml':'application/json',body:r.request().resourceType()==='image'?'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"/>':'{"data":[]}'}));
 await q.goto('http://latest.test');await q.locator('.bw2-console').waitFor();await q.locator('.card-frame').first().click();await q.locator('.bw2-detail').waitFor();
 await q.locator('.bw2-detail [data-close]').click();await q.locator('.tab-btn[data-tab="4"]').click();
 for(const key of ['bag','box','breeding','badge','pokedex','settings']){await q.locator('[data-page="'+key+'"]').click();await q.locator('.page-overlay.open').waitFor();await q.locator('.page-overlay.open [data-page-close]').click();}
 assert.deepEqual(latestErrors,[]);await q.close();
 remote=remote.replace("var PK_RUNTIME_DB='pk_hud_runtime_v1';","var PK_RUNTIME_DB='changed';");assert.equal(await p.evaluate(()=>__BW2_TEST.update.check()),false);assert.equal((await p.evaluate(()=>__BW2_TEST.update.snapshot())).prepared,null);assert.equal(await p.evaluate(()=>__BW2_TEST.update.install()),false);
 networkFail=true;assert.equal(await p.evaluate(()=>__BW2_TEST.update.check()),false);networkFail=false;remote='<html>Error page</html>';assert.equal(await p.evaluate(()=>__BW2_TEST.update.check()),false);
 remote=original;assert.equal(await p.evaluate(()=>__BW2_TEST.update.check()),false);assert.match((await p.evaluate(()=>__BW2_TEST.update.snapshot())).log,/已是最新/);
 const independent=fs.readFileSync(path.join(out,'独立版/宝可梦HUD-独立版.js'),'utf8');assert.ok(!independent.includes('function pkBeautyCheckUpdate')&&!independent.includes('var PK_BEAUTY_PACKAGE='));assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'更新流程验证.json'),JSON.stringify({passed:true,source:'actual upstream v3.3.19 plus synthetic v3.3.2',actualNewestComposedAndBooted:true,latestNativeBusinessFunctionsUnchanged:true,latestInstallUsesSynthesizedContent:true,actualNewestPages:['home','detail','bag','box','breeding','badge','pokedex','settings'],checkOnlyDoesNotInstall:true,concurrentCheckRequests:1,concurrentInstallWrites:1,copyIsSynthesized:true,writeBackFailureFallback:true,dbFailureDoesNotWrite:true,incompatibilityBlocked:true,networkFailureBlocked:true,invalidResponseBlocked:true,independentRemainsLean:true,realHostWriteBackTested:false,errors},null,2));console.log(JSON.stringify({passed:true,calls,realHostWriteBackTested:false}));
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

