const fs=require('fs'),path=require('path'),assert=require('assert/strict'),acorn=require('acorn');const{chromium}=require('./browser-runtime.cjs');const out=path.join(__dirname,'黑白2双版本-v0.3.9');
function functions(c){let m={};function w(n){if(!n||!n.type)return;if(n.type==='FunctionDeclaration')m[n.id.name]=c.slice(n.start,n.end);for(const v of Object.values(n))if(Array.isArray(v))v.forEach(w);else if(v&&v.type)w(v);}w(acorn.parse(c,{ecmaVersion:'latest'}));return m;}
const native=functions(JSON.parse(fs.readFileSync('pkm-hud-upstream.json','utf8')).content),contracts=['cardHTML','teamHTML','cardFromPkm','storePkm','withdrawPkm','moveBoxPkm','equipPkm','unequipPkmByCard','hudAssertPokemonMutable','hudRecordAssetMutation','pkmHudPersistStatData','pkmHudAuthoritativeAssetMutation','hudExternalStateChanged','hudEnsureLocationIndex','hudRebuildLocationIndex','resolvePkmImgs','resolveItemImgs','hudCachePutMany'];
(async()=>{const browser=await chromium.launch({headless:true,...require('./browser-runtime.cjs').launchOptions}),results=[];try{for(const variant of ['完整版','独立版']){
 const code=fs.readFileSync(path.join(out,variant,'宝可梦HUD-'+variant+'.js'),'utf8'),fn=functions(code);for(const key of contracts)assert.equal(fn[key],native[key],variant+' '+key);const page=await browser.newPage({viewport:{width:950,height:1350}}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));const html=fs.readFileSync(path.join(out,variant,'预览与测试.html'),'utf8');await page.route('**/*',r=>{requests.push(r.request().url());return r.request().url().startsWith('http://variant.test')?r.fulfill({contentType:'text/html',body:html}):r.request().resourceType()==='image'?r.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64')}):r.fulfill({contentType:'application/json',body:'{"data":[]}'});});await page.goto('http://variant.test');await page.locator('.bw2-console').waitFor();await page.waitForTimeout(400);const snapshots={};
 async function snap(name,selectors){await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));snapshots[name]=await page.evaluate(selectors=>selectors.map(selector=>{const n=document.querySelector(selector);if(!n)return {selector,missing:true};const r=n.getBoundingClientRect(),s=getComputedStyle(n);return {selector,text:selector.includes('info-inner')?'':n.textContent.trim(),rect:[r.width,r.height],styles:[s.color,s.backgroundColor,s.borderColor,s.fontSize,s.display,s.overflowY]};}),selectors);}
 await snap('home',['.bw2-profile','.card-frame','.bw2-menu-button','.nb-cell']);const head=await page.locator('.bw2-profile-head').count();await page.locator('[data-bw2-trainer]').click();await page.waitForTimeout(250);await snap('trainer',['.bw2-profile','.bw2-profile-body']);await page.locator('[data-bw2-trainer]').click();await page.locator('.nb-cell').first().click();await page.locator('.bw2-encounter').waitFor();await snap('nearby',['.bw2-encounter-info','.bw2-encounter-portrait','.bw2-encounter [data-action]']);await page.locator('.tab-btn[data-tab="1"]').click();await page.locator('.card-frame').first().click();await page.locator('.bw2-detail').waitFor();await snap('detail',['.bw2-summary-scene','.dt-move-cell','.bw2-detail-strips','.bw2-scene-held']);await page.locator('[data-bw2-info]').click();await page.locator('.pkm-hud-sub.open .modal.bw2-popup').waitFor();await snap('detailInfo',['.pkm-hud-sub .modal-body']);await page.locator('[data-sub-close]').click();await page.locator('.bw2-detail [data-close]').click();
 await page.locator('.tab-btn[data-tab="2"]').click();await snap('world',['#tab-2']);await page.locator('.tab-btn[data-tab="3"]').click();await snap('battle',['.bt-card','.bw2-command-grid']);await page.locator('[data-bw2-battle-toggle]').click();await snap('battleFolded',['.bw2-display-area','.bw2-control-area']);await page.locator('[data-bw2-battle-toggle]').click();await page.locator('.bw2-command-help').first().click();await snap('battleHelp',['.pkm-hud-overlay .modal-body']);await page.locator('.tab-btn[data-tab="4"]').click();
 for(const key of ['bag','box','breeding','badge','pokedex','map','typechart','settings']){
  await page.locator('[data-page="'+key+'"]').click();await page.locator('.page-overlay.open').waitFor();if(key==='pokedex'){await page.waitForLoadState('networkidle');await page.waitForFunction(()=>document.querySelector('.bw2-dex-toolbar'));}if(key==='pokedex')await page.evaluate(()=>__BW2_TEST.dexRender(Array.from({length:120},(_,i)=>({id:String(i+1),ndex:String(i+1),name:'测试精灵'+i})),null,{},{}));await snap(key,['.page-overlay.open .page','.page-overlay.open .page-body']);if(key==='box'){assert.equal(await page.locator('.bw2-box-card').count(),14);await page.locator('[data-bw2-box-tab="备用盒"]').click();assert.equal(await page.locator('.bw2-box-card').count(),0);await page.locator('[data-bw2-box-tab="盒子1"]').click();await page.locator('.bw2-box-card').first().click();assert.equal(await page.locator('.page-overlay.open').evaluate(n=>getComputedStyle(n).visibility),'hidden');await page.locator('.bw2-detail [data-close]').click();}if(key==='settings'){assert.equal(await page.locator('[data-pk-check-update]').count(),variant==='完整版'?1:0);await page.locator('[data-inline-h-open]').click();await page.locator('[data-inline-h-reset]').click();}await page.locator('.page-overlay.open [data-page-close]').click();
 }
 await page.locator('.tab-btn[data-tab="1"]').click();await page.setViewportSize({width:360,height:1200});await page.locator('.card-frame').first().click();await page.locator('.bw2-detail').waitFor();assert.ok(await page.locator('.bw2-summary-scene').evaluate(n=>n.getBoundingClientRect().width)>250);await page.locator('.bw2-detail [data-close]').click();await page.reload();await page.locator('.bw2-console').waitFor();await page.waitForTimeout(300);const business=await page.evaluate(()=>__BW2_TEST.business());assert.deepEqual(business,{stored:true,withdrawn:true,equipped:true,unequipped:true,pending:4});await page.waitForTimeout(150);assert.ok(await page.evaluate(()=>previewWrites)>0);assert.deepEqual(errors,[]);if(variant==='独立版')assert.equal(requests.filter(u=>u.includes('/pkm-hud/main/pkm-hud.js')).length,0);results.push({variant,snapshots,business,nativeContractsUnchanged:contracts,errors});await page.close();
 }
 const full=results[0].snapshots,ind=results[1].snapshots;for(const key of Object.keys(full))if(key!=='settings')assert.deepEqual(ind[key],full[key],'Visual difference: '+key);fs.writeFileSync(path.join(out,'双版本验证.json'),JSON.stringify({passed:true,visualPages:Object.keys(full).filter(k=>k!=='settings'),results},null,2));console.log(JSON.stringify({passed:true,variants:2,visualPages:Object.keys(full).length-1,business:results.map(r=>r.business)}));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});




