const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto'),acorn=require('acorn');
const {chromium,launchOptions}=require('../src/bw2/browser-runtime.cjs');
const root=path.join(__dirname,'..'),sha=s=>crypto.createHash('sha256').update(s).digest('hex');
function packageOf(code){let value;function visit(n){if(!n||!n.type)return;if(n.type==='VariableDeclarator'&&n.id.name==='PK_BEAUTY_PACKAGE')value=JSON.parse(code.slice(n.init.start,n.init.end));for(const v of Object.values(n))if(Array.isArray(v))v.forEach(visit);else if(v&&v.type)visit(v);}visit(acorn.parse(code,{ecmaVersion:'latest'}));return value;}
const bridge=`window.__KOJI_TEST={check:function(){return pkCheckUpdate();},install:function(){return pkDoUpdate();},snapshot:function(){return {core:PK_VER,ui:PK_BEAUTY_VER,prepared:kojiPrepared,log:document.getElementById('pk-update-msg')?.textContent};},record:function(){return pkSlotRead('active');},failDb:function(){pkInstallRecord=function(){return Promise.reject(new Error('mock database failure'));};},failWrite:function(){pkUpdateScript=function(){return Promise.resolve({ok:false});};}};`;
(async()=>{const browser=await chromium.launch({headless:true,...launchOptions}),results=[];
try{for(const channel of ['bw2','swsh']){
  const dir=path.join(root,'src',channel),version=require(path.join(dir,'package.json')).version;
  const folder=channel==='bw2'?path.join(dir,'黑白2双版本-v'+version,'完整版'):path.join(dir,'HUD美化版-交付');
  const code=fs.readFileSync(path.join(folder,channel==='bw2'?'宝可梦HUD-完整版.js':'宝可梦HUD-剑盾风格.js'),'utf8');
  const native=require('../src/shared/upstream-core.cjs')();
  const core=native.match(/var PK_VER='([^']+)'/)[1],nextCore=core.replace(/\d+$/,n=>Number(n)+1),nextUi=version.replace(/\d+$/,n=>Number(n)+1);
  const pkg=packageOf(code),future={...pkg,version:nextUi,beauty:pkg.beauty+'\n'+bridge};
  const scope={PK_BEAUTY_PACKAGE:future};vm.createContext(scope);vm.runInContext(future.runtime,scope);const futureCode=scope.pkBeautyBuildRemote(native);
  const currentManifest={schema:1,channel,ui:version,core};
  const futureManifest={schema:1,channel,ui:nextUi,core,script:'https://raw.githubusercontent.com/niheartent/pokemon_hud_koji/test/versions/'+channel+'/hud.js',sha256:sha(futureCode)};
  const template=fs.readFileSync(path.join(folder,channel==='bw2'?'预览与测试.html':'剑盾版预览.html'),'utf8');
  const marker=template.lastIndexOf('try{ensureHud();}catch(e){}');assert.ok(marker>0);const html=template.slice(0,marker)+bridge+'\n'+template.slice(marker);
  let manifest=currentManifest,upstream=native,release=futureCode,uiFail=false,coreFail=false;
  const errors=[],page=await browser.newPage({viewport:{width:1000,height:1400}});page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',async route=>{const url=route.request().url();
    if(url.startsWith('http://localhost:3217/'))return route.fulfill({contentType:'text/html',body:html});
    if(url.includes('/updates/'+channel+'.json'))return uiFail?route.abort():route.fulfill({contentType:'application/json',body:JSON.stringify(manifest)});
    if(url.includes('/versions/'+channel+'/hud.js'))return route.fulfill({contentType:'text/javascript',body:release});
    if(url.includes('/pkm-hud/main/pkm-hud.js'))return coreFail?route.abort():route.fulfill({contentType:'text/javascript',body:upstream});
    return route.fulfill({contentType:route.request().resourceType()==='image'?'image/svg+xml':'application/json',body:route.request().resourceType()==='image'?'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"/>':'{"data":[]}'});
  });
  await page.goto('http://localhost:3217/'+channel);await page.locator(channel==='bw2'?'.bw2-console':'.swsh-team').waitFor();
  await page.locator('.tab-btn[data-tab="4"]').click();await page.locator('[data-page="settings"]').click();
  assert.equal(await page.evaluate(()=>__KOJI_TEST.check()),false,'no changes');
  upstream=native.replace("var PK_VER='"+core+"';","var PK_VER='"+nextCore+"';");
  assert.equal(await page.evaluate(()=>__KOJI_TEST.check()),true,'core only');
  assert.equal((await page.evaluate(()=>__KOJI_TEST.snapshot())).prepared.ui,version);
  manifest=futureManifest;assert.equal(await page.evaluate(()=>__KOJI_TEST.check()),true,'both versions');
  let state=await page.evaluate(()=>__KOJI_TEST.snapshot());assert.equal(state.prepared.ui,nextUi);assert.equal(state.prepared.core,nextCore);
  // A corrupt UI download must not contaminate the available core update.
  release=futureCode+'\n/*tampered*/';assert.equal(await page.evaluate(()=>__KOJI_TEST.check()),true);
  assert.equal((await page.evaluate(()=>__KOJI_TEST.snapshot())).prepared.ui,version);release=futureCode;
  manifest={...futureManifest,channel:channel==='bw2'?'swsh':'bw2'};upstream=native;assert.equal(await page.evaluate(()=>__KOJI_TEST.check()),false,'cross-channel blocked');
  manifest=futureManifest;upstream=upstream.replace('function pkDoUpdate(','function missingCoreUpdate(');
  assert.equal(await page.evaluate(()=>__KOJI_TEST.check()),true,'UI release survives incompatible upstream');
  assert.equal((await page.evaluate(()=>__KOJI_TEST.snapshot())).prepared.core,core);
  coreFail=true;assert.equal(await page.evaluate(()=>__KOJI_TEST.check()),true,'UI release survives upstream network failure');coreFail=false;upstream=native;
  manifest=currentManifest;uiFail=true;upstream=native.replace("var PK_VER='"+core+"';","var PK_VER='"+nextCore+"';");
  assert.equal(await page.evaluate(()=>__KOJI_TEST.check()),true,'core survives UI network failure');uiFail=false;
  manifest=currentManifest;upstream=native.replace("var PK_VER='"+core+"';","var PK_VER='"+nextCore+"';");
  assert.equal(await page.evaluate(()=>__KOJI_TEST.check()),true,'pinned latest interfaces with synthetic core increment');
  const actual=await page.evaluate(()=>__KOJI_TEST.snapshot());assert.equal(actual.prepared.core,nextCore);
  const bootCode=actual.prepared.content,bootIndex=bootCode.lastIndexOf('try{ensureHud();}catch(e){}'),start=template.lastIndexOf('<script>'),end=template.lastIndexOf('</script>');
  const actualHtml=template.slice(0,start+8)+(bootCode.slice(0,bootIndex)+bridge+bootCode.slice(bootIndex)).replaceAll('</script','<\\/script')+template.slice(end);
  const actualPage=await browser.newPage({viewport:{width:1000,height:1400}});actualPage.on('pageerror',e=>errors.push(channel+': '+e.stack));await actualPage.route('**/*',r=>r.request().url().startsWith('http://localhost:3218/')?r.fulfill({contentType:'text/html',body:actualHtml}):r.fulfill({contentType:r.request().resourceType()==='image'?'image/svg+xml':'application/json',body:r.request().resourceType()==='image'?'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"/>':'{"data":[]}'}));
  await actualPage.goto('http://localhost:3218/'+channel);await actualPage.locator(channel==='bw2'?'.bw2-console':'.swsh-team').waitFor();assert.equal((await actualPage.evaluate(()=>__KOJI_TEST.snapshot())).core,nextCore);await actualPage.close();
  // Persist a UI-only update to real browser IndexedDB, then boot it after reload.
  manifest=futureManifest;upstream=native;await page.evaluate(()=>__KOJI_TEST.failWrite());
  assert.equal(await page.evaluate(()=>__KOJI_TEST.check()),true);
  state=await page.evaluate(()=>__KOJI_TEST.snapshot());assert.equal(state.prepared.core,core);assert.equal(state.prepared.ui,nextUi);
  assert.deepEqual(await page.evaluate(()=>Promise.all([__KOJI_TEST.install(),__KOJI_TEST.install()])),[true,false]);
  const record=await page.evaluate(()=>__KOJI_TEST.record());assert.equal(record.contentSha,sha(record.content));
  manifest={...currentManifest,ui:nextUi};await page.reload();await page.waitForFunction(v=>window.__KOJI_TEST&&__KOJI_TEST.snapshot().ui===v,nextUi);
  await page.locator(channel==='bw2'?'.bw2-console':'.swsh-team').waitFor();
  await page.locator('.tab-btn[data-tab="4"]').click();await page.locator('[data-page="settings"]').click();
  await page.waitForFunction(async()=>{const record=await __KOJI_TEST.record();return record&&record.health==='healthy';});const healthy=await page.evaluate(()=>__KOJI_TEST.record());assert.equal(healthy.health,'healthy');
  const secondUi=nextUi.replace(/\d+$/,n=>Number(n)+1),secondPkg={...future,version:secondUi};const secondScope={PK_BEAUTY_PACKAGE:secondPkg};vm.createContext(secondScope);vm.runInContext(secondPkg.runtime,secondScope);release=secondScope.pkBeautyBuildRemote(native);manifest={...futureManifest,ui:secondUi,sha256:sha(release)};await page.evaluate(()=>__KOJI_TEST.failWrite());assert.equal(await page.evaluate(()=>__KOJI_TEST.check()),true);assert.equal(await page.evaluate(()=>__KOJI_TEST.install()),true);manifest={...currentManifest,ui:secondUi};await page.reload();await page.waitForFunction(v=>window.__KOJI_TEST&&__KOJI_TEST.snapshot().ui===v,secondUi);
  assert.deepEqual(errors,[]);results.push({channel,core,ui:version,nextUi,pinnedLatestInterfacesComposedAndBooted:true,coreOnly:true,uiOnlyReloaded:true,twoConsecutiveUiUpdatesReloaded:true,both:true,checksumTamperingBlocked:true,crossChannelBlocked:true,incompatibleUpstreamUiFallback:true,independentNetworkFailures:true,concurrentInstallSingleWrite:true,realIndexedDbHealthy:true,realHostWriteBackTested:false});await page.close();
}fs.mkdirSync(path.join(root,'artifacts'),{recursive:true});fs.writeFileSync(path.join(root,'artifacts/remote-update-tests.json'),JSON.stringify({passed:true,results},null,2));console.log(JSON.stringify({passed:true,channels:results}));
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
