/* Empty-slot regression: isolated fake host and mocked external resources. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('./browser-runtime.cjs');
const out=path.join(__dirname,'HUD美化版-交付'),html=fs.readFileSync(path.join(out,'剑盾版预览.html'),'utf8').replace('window.__SWSH_TEST={', `fetchItemSprite=function(name,en,callback){callback('data:image/svg+xml;base64,'+btoa('<svg xmlns="http://www.w3.org/2000/svg" width="28" height="28"><circle cx="14" cy="14" r="12" fill="'+(en==='great-ball'?'blue':'red')+'"/></svg>'));};window.__SWSH_TEST={`);
(async()=>{const browser=await chromium.launch({headless:true,...require('./browser-runtime.cjs').launchOptions}),errors=[],cases=[];
try{const page=await browser.newPage({viewport:{width:1000,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{if(r.request().url().startsWith('http://slots.test'))return r.fulfill({contentType:'text/html',body:html});if(r.request().resourceType()==='image')return r.continue();return r.fulfill({contentType:'application/json',body:'{"data":[]}'});});await page.goto('http://slots.test');await page.locator('.swsh-team').waitFor();await page.evaluate(()=>{Object.values(previewState.队伍).forEach((p,i)=>{p.精灵球=i%2?'超级球':'精灵球';p.精灵球英文=i%2?'great-ball':'poke-ball';});window.__slotTeam=JSON.parse(JSON.stringify(previewState.队伍));});
for(const width of [1000,360])for(const dark of [false,true])for(const keep of [[1,2,3,4,5,6],[1,2,3,4,5],[1,3,6],[2,5],[4],[]]){
 await page.setViewportSize({width,height:1000});await page.evaluate(async({keep,dark})=>{previewState.队伍={};keep.forEach(slot=>previewState.队伍[slot]=JSON.parse(JSON.stringify(__slotTeam[slot])));document.querySelector('#pkm-hud-inline').classList.toggle('swsh-dark',dark);await __SWSH_TEST.refresh();document.querySelector('#pkm-hud-inline').classList.toggle('swsh-dark',dark);},{keep,dark});
 await page.waitForFunction(n=>document.querySelectorAll('.swsh-party-list>.card-frame').length===n,keep.length);
 const snapshot=await page.evaluate(()=>{const team=document.querySelector('.swsh-team'),list=team.querySelector('.swsh-party-list'),rows=Array.from(list.querySelectorAll(':scope>.card-frame,:scope>.empty-frame'));return {slots:rows.map(row=>+row.getAttribute('data-swsh-party-slot')),empty:rows.filter(row=>row.classList.contains('empty-frame')).map(row=>row.textContent.trim()),teamHeight:team.getBoundingClientRect().height,emptyHidden:rows.filter(row=>row.classList.contains('empty-frame')).every(row=>getComputedStyle(row).visibility==='hidden'&&getComputedStyle(row.querySelector('.empty-txt')).visibility==='hidden'),count:team.querySelector('.swsh-party-heading>span:last-child').textContent,escapedEmpty:document.querySelectorAll('.empty-frame').length-list.querySelectorAll('.empty-frame').length,oldEmptyBorderHidden:Array.from(list.querySelectorAll('.empty-frame .card-bg-svg'),el=>getComputedStyle(el).display).every(display=>display==='none'),rowHeights:rows.map(row=>row.getBoundingClientRect().height),listHeight:list.getBoundingClientRect().height,horizontalOverflow:document.documentElement.scrollWidth>innerWidth};});
 assert.deepEqual(snapshot.slots,[1,2,3,4,5,6]);assert.equal(snapshot.count,keep.length+' / 6');assert.equal(snapshot.empty.length,6-keep.length);assert.equal(snapshot.escapedEmpty,0);assert.equal(snapshot.emptyHidden,true);assert.equal(snapshot.oldEmptyBorderHidden,true);assert.equal(snapshot.horizontalOverflow,false);
 assert(Math.max(...snapshot.rowHeights)-Math.min(...snapshot.rowHeights)<.5,'occupied and empty slots differ in height '+JSON.stringify({width,dark,keep,heights:snapshot.rowHeights}));var baseline=cases.find(c=>c.width===width&&c.dark===dark&&c.keep.length===6);if(baseline){assert(Math.abs(baseline.listHeight-snapshot.listHeight)<.5,'party shrank after Pokemon removed');assert(Math.abs(baseline.teamHeight-snapshot.teamHeight)<.5,'team panel shrank after Pokemon removed');}
 if(keep.length<6){assert.equal(await page.locator('.swsh-party-list>.empty-frame').first().isVisible(),false);assert.equal(await page.locator('.pkm-hud-overlay.open').count(),0);}
 if(keep.length){assert.equal(await page.locator('.swsh-preview-ball').getAttribute('data-ball'),keep[0]%2?'精灵球':'超级球');assert.equal(await page.locator('.swsh-preview-ball img').count(),1);const metrics=await page.locator('.swsh-party-list>.card-frame').first().evaluate(row=>({padding:parseFloat(getComputedStyle(row.querySelector('.card-inner')).paddingRight),inset:row.getBoundingClientRect().right-row.querySelector('.hp-bar').getBoundingClientRect().right,button:document.querySelector('[data-party-step]').getBoundingClientRect().height,ball:document.querySelector('.swsh-preview-ball img').getBoundingClientRect().width}));assert(metrics.padding>=22&&metrics.inset>=21);assert(Math.abs(metrics.button-30)<.5&&Math.abs(metrics.ball-22)<.5);}
 if(keep.length>1){await page.locator('[data-party-step="1"]').click();assert.equal(await page.locator('.swsh-selected').getAttribute('data-slot'),String(keep[1]));assert.equal(await page.locator('.swsh-preview-ball').getAttribute('data-ball'),keep[1]%2?'精灵球':'超级球');assert.equal(await page.locator('.swsh-preview-ball img').count(),1);}else if(!keep.length){assert.equal(await page.locator('.swsh-focus-empty').innerText(),'暂无同行宝可梦');assert.equal(await page.locator('[data-party-step]:disabled').count(),2);}
 if(width===1000&&dark&&keep.length===5)await page.locator('.swsh-team').screenshot({path:path.join(out,'预览-五只与空位.png')});if(width===1000&&dark&&!keep.length)await page.locator('.swsh-team').screenshot({path:path.join(out,'预览-六个空位.png')});
 cases.push({width,dark,keep,...snapshot});
}
assert.equal(await page.evaluate(()=>previewWrites),0);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'空位验证.json'),JSON.stringify({passed:true,cases,errors,presentationWrites:0},null,2));console.log(JSON.stringify({passed:true,cases:cases.length,heightSamples:cases.filter(c=>c.width===1000&&!c.dark).map(c=>({keep:c.keep,heights:c.rowHeights,list:c.listHeight}))}));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

