/* Headless fake host, update responses mocked. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('./browser-runtime.cjs');
const out=path.join(__dirname,'HUD美化版-交付'),html=fs.readFileSync(path.join(out,'剑盾版预览.html'),'utf8'),original=require('../shared/upstream-core.cjs')(),manifest=JSON.parse(fs.readFileSync(path.join(out,'构建信息.json'),'utf8'));
(async()=>{const browser=await chromium.launch({headless:true,...require('./browser-runtime.cjs').launchOptions}),errors=[];
try{
 const page=await browser.newPage({viewport:{width:1000,height:1000}});let remote=original.replace("var PK_VER='"+manifest.core+"';","var PK_VER='"+manifest.core.replace(/(\d+)$/,v=>Number(v)+1)+"';");
 const logFixture='测试上游更新日志\n第二行 <img src=x onerror="window.__logExecuted=1">';remote=remote.replace(/\/\*PK_NOTICE_BEGIN[\s\S]*?PK_NOTICE_END\*\//,'/*PK_NOTICE_BEGIN\n'+logFixture+'\nPK_NOTICE_END*/');
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>{const url=r.request().url();if(url.startsWith('http://swsh-preview.test'))return r.fulfill({contentType:'text/html',body:html});if(r.request().url().includes('/updates/swsh.json'))return r.fulfill({contentType:'application/json',body:JSON.stringify({schema:1,channel:'swsh',ui:manifest.ui,core:manifest.core})});if(r.request().resourceType()==='image')return r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"/>'});return r.fulfill({contentType:url.includes('pkm-hud.js')?'text/javascript':'application/json',body:url.includes('pkm-hud.js')?remote:'{"data":[]}'});});
 await page.addInitScript(()=>localStorage.setItem('pk_swsh_dark_theme','0'));
 await page.goto('http://swsh-preview.test');await page.locator('.swsh-team').waitFor();
 assert.equal(await page.locator('.swsh-party-list .card-frame').count(),6);
 await page.locator('.swsh-party-list .card-frame[data-slot="2"]').hover();assert.equal(await page.locator('.swsh-selected').getAttribute('data-slot'),'2');
 await page.locator('[data-party-step="1"]').click();assert.equal(await page.locator('.swsh-selected').getAttribute('data-slot'),'3');
 await page.locator('[data-party-step="-1"]').click();assert.equal(await page.locator('.swsh-selected').getAttribute('data-slot'),'2');
 await page.locator('.swsh-party-list .card-frame[data-slot="1"]').click();await page.locator('.pkm-hud-overlay.open .dt-move-grid').waitFor();
 assert.equal(await page.locator('.pkm-hud-overlay.open .dt-move-cell').count(),4);assert.equal(await page.locator('.pkm-hud-overlay.open .dt-move-cell').first().getAttribute('data-mvcat'),'特殊');
 await page.locator('.pkm-hud-overlay.open:not(.pkm-hud-sub) [data-close]').click();
 await page.locator('.hud').screenshot({path:path.join(out,'预览-剑盾浅色.png')});
 await page.locator('.tab-btn[data-tab="4"]').click();await page.locator('#tab-4 [data-page="settings"]').click();await page.locator('.page-overlay.open').waitFor();
 const settings=await page.locator('.page-overlay.open').innerText();assert(settings.includes(manifest.core)&&settings.includes(manifest.ui),settings);
 await page.locator('[data-toggle="swsh-dark"]').check();assert.equal(await page.locator('#pkm-hud-inline').evaluate(el=>el.classList.contains('swsh-dark')),true);
 await page.locator('[data-swsh-hud-width]').evaluate(el=>{el.value='800';el.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal(await page.evaluate(()=>localStorage.getItem('pk_swsh_hud_width')),'800');
 await page.locator('[data-swsh-hud-width-reset]').click();assert.equal(await page.evaluate(()=>localStorage.getItem('pk_swsh_hud_width')),null);
 await page.locator('[data-pk-check-update]').click();await page.waitForFunction(()=>document.querySelector('[data-pk-do-update]').style.display==='block');
 const compatible=await page.locator('.page-overlay.open').innerText();assert(compatible.includes('已合成并检查')); 
 const logs=page.locator('[data-swsh-update-logs]');assert.equal((await logs.locator('.swsh-update-log-text').first().textContent()).trim(),logFixture);assert.equal(await logs.locator('img').count(),0);assert.equal(await page.evaluate(()=>!!window.__logExecuted),false);assert.equal(await logs.locator('details').first().getAttribute('open'),'');await logs.locator('details').nth(1).locator('summary').click();assert((await logs.innerText()).includes('修复白天主题的训练家'));
 remote=remote.replace('function teamHTML()','function teamNewHTML()');await page.locator('[data-pk-check-update]').click();await page.waitForFunction(()=>document.querySelector('.page-overlay.open').textContent.includes('不兼容'));
 assert.equal(await page.locator('[data-pk-do-update]').evaluate(el=>el.style.display),'none');
 assert((await logs.locator('.swsh-update-log-text').first().textContent()).includes('测试上游更新日志'));
 remote=original.replace("var PK_VER='"+manifest.core+"';","var PK_VER='"+manifest.core.replace(/(\d+)$/,v=>Number(v)+1)+"';").replace(/\/\*PK_NOTICE_BEGIN[\s\S]*?PK_NOTICE_END\*\//,'');await page.locator('[data-pk-check-update]').click();await page.waitForFunction(()=>document.querySelector('[data-pk-do-update]').style.display==='block');assert((await logs.innerText()).includes('上游未提供该版本的更新日志。'));
 remote=original;await page.locator('[data-pk-check-update]').click();await page.waitForFunction(()=>document.querySelector('#pk-update-msg').textContent.includes('已是最新版本'));assert((await logs.innerText()).includes((original.match(/\/\*PK_NOTICE_BEGIN([\s\S]*?)PK_NOTICE_END\*\//)||[])[1].trim()));assert((await logs.locator('summary').first().innerText()).includes(manifest.core));await page.locator('.set-opts:has([data-pk-check-update])').screenshot({path:path.join(out,'预览-更新日志.png')});
 await page.locator('.page-overlay.open [data-page-close]').click();await page.locator('.tab-btn[data-tab="1"]').click();
 await page.locator('.hud').screenshot({path:path.join(out,'预览-剑盾暗色.png')});
 await page.locator('.quick-chip[data-page="box"]').click();await page.locator('.page-overlay.open').waitFor();await page.locator('.page-overlay.open [data-page-close]').click();
 // Native command handlers may replace textContent; the decoration must recover.
 await page.evaluate(()=>{var input=document.createElement('textarea');input.id='send_textarea';document.body.appendChild(input);});
 await page.locator('.tab-btn[data-tab="3"]').click();await page.locator('.cmd-panel summary').click();var command=await page.locator('.cmd-panel .cmd-btn').first().getAttribute('data-cmd');await page.locator('.cmd-panel .cmd-btn').first().click();assert.equal(await page.locator('#send_textarea').inputValue(),command);await page.waitForTimeout(1400);assert.equal(await page.locator('.cmd-panel .cmd-btn').first().locator('.swsh-cmd-label').count(),1);
 await page.locator('.tab-btn[data-tab="1"]').click();
 await page.setViewportSize({width:360,height:950});await page.locator('.swsh-team').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'horizontal overflow');await page.locator('.hud').screenshot({path:path.join(out,'预览-剑盾窄屏.png')});
 assert.equal(await page.evaluate(()=>previewWrites),0);assert.deepEqual(errors,[]);
 // A synthetic upstream adds visible features. Verify the native data survives.
 let extended=original.replace('return \'<div class="grid"><div class="col col-left">','return \'<div class="grid"><div data-upstream-extra>上游新增队伍提示</div><div class="col col-left">').replace("var content=infoRow('名字'","var content=infoRow('新增资料','上游新增训练家资料')+infoRow('名字'").replace('var rows=CMDS.map','var rows=CMDS.concat([["新增快捷指令","新增测试指令","新增说明"]]).map');
 for(const marker of ['data-upstream-extra','上游新增训练家资料','新增快捷指令'])assert(extended.includes(marker),'fixture missing '+marker);
 assert.notEqual(extended,original);const merged=await page.evaluate(raw=>__SWSH_TEST.build(raw),extended),start=html.lastIndexOf('<script>'),end=html.lastIndexOf('</script>'),extendedHTML=html.slice(0,start+8)+merged.replaceAll('</script','<\\/script')+html.slice(end);
 const extraPage=await browser.newPage({viewport:{width:1000,height:1000}});extraPage.on('pageerror',e=>errors.push(e.message));await extraPage.route('**/*',r=>{if(r.request().url().startsWith('http://swsh-extra.test'))return r.fulfill({contentType:'text/html',body:extendedHTML});if(r.request().url().includes('/updates/swsh.json'))return r.fulfill({contentType:'application/json',body:JSON.stringify({schema:1,channel:'swsh',ui:manifest.ui,core:manifest.core})});if(r.request().resourceType()==='image')return r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"/>'});return r.fulfill({contentType:'application/json',body:'{"data":[]}'});});await extraPage.goto('http://swsh-extra.test');await extraPage.locator('.swsh-team').waitFor();assert.equal(await extraPage.locator('[data-upstream-extra]').innerText(),'上游新增队伍提示');await extraPage.locator('.swsh-trainer-details summary').click();assert((await extraPage.locator('.swsh-trainer-details-body').innerText()).includes('上游新增训练家资料'));await extraPage.locator('.tab-btn[data-tab="3"]').click();assert.equal(await extraPage.locator('.cmd-panel .cmd-btn').count(),8);assert((await extraPage.locator('.cmd-panel .cmd-btn').last().textContent()).includes('新增快捷指令'));assert.equal(await extraPage.evaluate(()=>previewWrites),0);await extraPage.close();assert.deepEqual(errors,[]);
 const result={passed:true,core:manifest.core,ui:manifest.ui,scope:'隔离浏览器、模拟MVU和更新响应，未操作真实酒馆',partyHoverAndArrows:true,nativeDetailMoves:true,themeAndWidth:true,updateButtonGating:true,upstreamAndBeautyLogs:true,incompatibleReleaseLog:true,emptyLogFallback:true,logEscaped:true,boxRoute:true,nativeCommandHandler:true,nativeNewTeamContent:true,nativeNewTrainerField:true,nativeNewCommand:true,narrowNoOverflow:true,presentationWrites:0,errors};fs.writeFileSync(path.join(out,'界面兼容验证.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

